name: Setup

on:
  push:

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      # setup
      - uses: actions/checkout@v4

      # GitHub Actions
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

      - name: build
        run: |
          docker compose build
        working-directory: builds
